#ifndef ALBW_FLURRY_PROC_H
#define ALBW_FLURRY_PROC_H

#include "mods/api.h"

// ============================================
// Flurry Rush attack proc - the alink proc OVERLAY.
//
// The fork implemented the rush as a new daAlink_c proc, PROC_FLURRY_RUSH
// (fork id 0x162, fork d_a_alink.h:1372, table row fork d_a_alink.cpp:2116).
// The stock exe has no proc-table slot for it and adding an id would index
// past daAlink_c::m_procInitTable, so - exactly as Hurricane Spin does - the
// proc is OVERLAID on an existing valid proc:
//
//   host proc      PROC_CUT_NORMAL   (stock d_a_alink.h:1053)
//   per-frame      procCutNormal     (stock :1900)  PRE + HOOK_SKIP_ORIGINAL
//   re-entry guard procCutNormalInit (stock :1899)  PRE + HOOK_SKIP_ORIGINAL
//
// The twelve fork methods are kept BYTE-VERBATIM on a layout-compatible
// daAlink_c subclass (AlbwFlurry_c), the outfit_swim.cpp technique - see
// flurry_proc.cpp and src/flurry_port.inc (generated by
// tools/port/port_tool.py from tools/port/flurry.json).
// ============================================

class daAlink_c;

// Donor procFlurryRushInit (fork d_a_alink_flurry.inc:243-278) behind the
// overlay. Returns the donor's own return value: 0 = not armed, Link's proc
// untouched; non-zero = the overlay now owns Link and the caller must NOT run
// its own proc init.
//
// Called from the two seams the donor calls it from:
//   fork d_a_alink.cpp:17614-17620  procSideStepLandInit (first statement)
//   fork d_a_alink.cpp:18378-18386  procBackJumpLandInit (first statement)
int albw_flurry_proc_try_enter(daAlink_c* link);

// True while the overlay owns Link's proc.
bool albw_flurry_proc_active();

// Per-frame lifetime backstop, called once from mod_update (via
// albw_flurry_tick). The primary end is the commonProcInit chokepoint below;
// this catches an overlay left standing when the player actor itself went
// away (stage change, death, transform) and never passed through it.
void albw_flurry_proc_frame_watch();

// Installs the procCutNormal / procCutNormalInit / commonProcInit hooks.
ModResult albw_flurry_proc_init(ModError* error);

// Clears the overlay unconditionally (mod shutdown).
void albw_flurry_proc_reset();

#endif  // ALBW_FLURRY_PROC_H
